<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

/* =================================================================*/
/* =                 OVERALL LAYOUT  
/* =================================================================*/


/*
 * Swap in a different sidebar instead of the default sidebar.*/
function child_sidebar_logic() {
    remove_action( 'genesis_after_content', 'genesis_get_sidebar' );
    add_action( 'genesis_after_content', 'child_get_blog_sidebar' );
}
//add_action( 'get_header', 'child_sidebar_logic' );

/*
 * Retrieve blog sidebar */
function child_get_blog_sidebar() {
    get_sidebar( 'social' );
}

// Apply Full Width Content layout
function bp_set_full_layout() {
	// Force full width content
	add_filter( 'genesis_pre_get_option_site_layout', '__genesis_return_full_width_content' );
}
add_action( 'get_header', 'bp_set_full_layout' );


/* =================================================================*/
/* =                 CONTENT
/* =================================================================*/


//* Remove the breacrumbs
/**
 * I used genesis_before, but you can also use get_header or other hooks as long
 * as you call the check function prior to the breadcrumbs being called.
 */
add_action( 'genesis_before', 'wps_remove_genesis_breadcrumbs' );
function wps_remove_genesis_breadcrumbs() {
    remove_action( 'genesis_before_loop', 'genesis_do_breadcrumbs' );
}

//* Remove the entry title (requires HTML5 theme support)
add_action( 'genesis_before', 'wps_remove_genesis_entry_header' );
function wps_remove_genesis_entry_header() {
	remove_action( 'genesis_entry_header', 'genesis_do_post_title' );
}


/* =================================================================*/
/* =                 WIDGETS
/* =================================================================*/


//* Hook category widget area after post content
function add_social_widgeted_area() {
	
		if (!bp_is_register_page())
	    genesis_widget_area( 'social-bottom', array(
	        'before' => '<div class="social-bottom widget-area">',
	        'after'  => '</div>',
    	));
}
add_action( 'genesis_after_loop', 'add_social_widgeted_area' );
 


genesis();
